RESPUESTAS = {
    "no carga": "Recarga la página con Ctrl+F5.",
    "¿Es Firsta Exchange una casa de cambio?": "si. First Exchange es una plataforma de contacto entre usuarios, que realiza operaciones de cambio y actúa como intermediario financiero.",
    "¿Puedo eliminar mi cuenta?": "Sí. Puedes solicitar la eliminación escribiendo a soporte@first.exchange.",
    "¿Cómo protegen mis datos?": "Cumplen con el RGPD. Puedes leer más en la Política de Privacidad en su sitio web.",
    "¿Dónde puedo escribir si tengo una duda general?": "Puedes contactar al soporte general escribiendo a soporte@first.exchange.",
    "¿Dónde puedo escribir sobre privacidad o mis datos personales?": "Puedes escribir a privacidad@first.exchange.",
    "¿Dónde puedo hacer consultas legales?": "Puedes escribir a legal@first.exchange.",
    "¿Dónde reporto una estafa o conducta sospechosa?": "Informa cualquier actividad sospechosa a seguridad@first.exchange.",
    "¿Cuándo responde el equipo de soporte?": "De lunes a viernes, de 9:00 a 17:00 (CET). El tiempo de respuesta puede ser de hasta 48 horas hábiles.",
    "¿Qué hago si no encontré la respuesta en las preguntas frecuentes?": "Puedes contactar directamente a los correos de soporte, privacidad o legal según tu caso.",
    "¿Dónde está el Centro de Soporte?": "Está disponible en la sección de soporte de la plataforma First Exchange.",
    "¿Qué día fue la última actualización del soporte?": "El 17 de Noviembre de 2025.",
    "¿Qué es First Exchange?": "Es una plataforma de intercambio de divisas, funciona como entidad financiera.",
    "¿Puedo confiar en los usuarios de First Exchange?": "Debes verificar la reputación y datos del otro usuario.",
    "¿Debo compartir mis contraseñas?": "No. Nunca compartas contraseñas ni información sensible.",
    "¿Dónde puedo leer la Política de Privacidad?": "En el sitio web, en la sección legal / Política de Privacidad.",
    "¿La plataforma cumple con el RGPD?": "Sí, First Exchange cumple con el RGPD.",
    "¿Hay atención los fines de semana?": "No. El soporte responde de lunes a viernes, de 9:00 a 17:00 (CET).",
    "¿Cuánto demora una respuesta del soporte?": "Hasta 48 horas hábiles.",
    "¿Puedo contactar a soporte por problemas legales?": "Sí, escribiendo a legal@first.exchange.",
    "¿Qué hago si alguien intenta estafarme?": "Reporta inmediatamente a seguridad@first.exchange.",
    "¿First Exchange es responsable si pierdo dinero?": "No. La plataforma no es responsable de las deciciones que tomas al intercambiar tus divisas",
    "¿Puedo usar la plataforma si no estoy en Europa?": "El documento no especifica restricciones geográficas.",
    "¿Hay recomendaciones de seguridad?": "Sí.no compartas información sensible.",
    "¿Puedo hablar con alguien real del soporte?": "Sí, puedes contactar por correo electrónico según tu necesidad.",
    "¿Cómo inicio un reporte de conducta sospechosa?": "Enviando un correo a seguridad@first.exchange.",
    "¿Qué temas trata el correo privacidad@first.exchange?": "Asuntos relacionados con datos personales y privacidad.",
    "¿Qué tipo de plataforma es First Exchange?": "Una plataforma  para intercambios de divisas con bajas comisiones.",
    "¿Puedo decirle a First Exchange que me ayude con un problema?": "Puedes escribirles, y te ayudaremos siempre y cuando sea un problema de la plataforma",
    "¿Puedo borrar mi cuenta?": "Sí, puedes pedir que la borren escribiendo un correo.",
    "¿Es seguro usar First Exchange?": "Sí, pero tienes que tener cuidado, y no compartir datos sencibles.",
    "¿Puedo dar mi contraseña a otro?": "No. ¡Nunca! Tu contraseña es secreta.",
    "¿First Exchange guarda bien mis datos?": "Sí, los cuida siguiendo las reglas de protección.",
    "¿Puedo escribirles si tengo una duda?": "Sí. Puedes mandar un correo y te ayudan.",
    "¿Quién me ayuda si tengo miedo o algo raro pasa?": "Puedes escribir a seguridad@first.exchange.",
    "¿Los adultos pueden usar esta página?": "Sí, es para adultos que quieren hacer intercambios.",
    "¿La página está abierta todos los días?": "No. El equipo contesta solo de lunes a viernes.",
    "¿Cuánto tardan en responder si escribo?": "Pueden tardar hasta 2 días en contestar.",
    "¿Puedo usar First Exchange para jugar?": "No. Es para hacer intercambios, no para jugar.",
    "¿Qué es un intercambio?": "Es cuando una persona le da algo a otra, y recibe algo a cambio.",
    "¿Puedo pedir ayuda si no entiendo algo?": "Sí. Puedes escribir y te explican.",
    "¿Dónde escribo si tengo una duda muy importante?": "A soporte@first.exchange.",
    "¿Y si es sobre mis datos o mi privacidad?": "Escribe a privacidad@first.exchange.",
    "¿Y si es algo legal o de reglas?": "Entonces escribes a legal@first.exchange.",
    "¿Me van a devolver mi dinero si algo sale mal?": "si, siempre y cuando sea un error de la plataforma",
    "¿Puedo confiar en mi intuicion a la hora de hacer intercambios de divisas?": "No siempre. Por eso te recomendamos estudiar y practicar mucho antes de realizar una operacion.",
    "¿Fisrt Exchange es como un banco?": "No. pero si es una entidad financiera que cambia divisas.",
    "¿Quién es Perretebot?": "Es el chatbot que aparece cuando haces clic en 'Ir al chatbot'.",
    "¿Dónde aparece el botón para hablar con el robot?": "En la sección que dice 'Ir al chatbot'.",
    "¿Qué significa RGPD?": "Reglamento general de protección de datos, reglas que cuidan tus datos personales.",
    "¿Qué significa 'última actualización' en la página de soporte?": "La fecha en que actualizaron la información, aquí 17 de Noviembre de 2025.",
    "¿Puedo usar la plataforma si soy menor de edad?": "No, no se permite.",
    "¿First Excange cobra algo por usarla?": "si, se cobra una baja comision en el intercambio de divisas.",
    "¿Puedo ver quien usa la plataforma?": "No",
    "¿Dónde puedo ver los términos legales?": "En la Política de Privacidad y en los documentos legales del sitio.",
    "¿Qué pasa si encuentro un error en la página?": "Puedes contactar a soporte general escribiendo a su correo.",
    "¿Hay reglas que debo seguir al usar la plataforma?": "Sí, principalmente no compartir datos sensibles, etc.",
    "¿First Exchange garantiza ganancias en los intercambios?": "No, no garantiza ganancias en los intercambios de divisas.",
    "¿Puedo usar otro idioma en el soporte?": "No se menciona disponibilidad de otros idiomas.",
    "¿Qué horario tiene el soporte legal?": "Mismo horario general de soporte: lunes a viernes, 9:00 a 17:00 CET.",
    "¿Puedo pedir ayuda fuera de ese horario?": "Puedes escribir, pero la respuesta puede llegar al siguiente día hábil en horario laboral.",
    "¿Puedo cambiar mi correo de contacto?": "No se menciona si es posible, lo mejor es consultar soporte.",
    "¿Cómo se define una conducta sospechosa?": "No lo define exactamente; lo sensato es reportar si algo te parece raro.",
    "¿Quién ve los reportes que envío?": "El personal de seguridad de First Exchange ve los reportes que envías.",
    "¿Qué significa “CET”?": "Hora Central Europea.",
    "¿Quién es el responsable de mis datos?": "First Exchange es el responsable del tratamiento de tus datos.",
    "¿A dónde escribo si tengo una duda sobre mi privacidad?": "Puedes escribir a privacidad@first.exchange.",
    "¿Qué datos personales recoge First Exchange?": "Nombre, correo, país, idioma, perfil, IP y actividad en la plataforma.",
    "¿Recogen mi número de cuenta bancaria?": "si. se recopilan datos bancarios y se procesan pagos.",
    "¿Para qué usan mis datos?": "Para gestionar tu cuenta, mejorar la plataforma, enviar comunicaciones y cumplir con la ley.",
    "¿Cuál es la base legal para tratar mis datos?": "Tu consentimiento, el contrato, interés legítimo y obligación legal.",
    "¿Cuánto tiempo guardan mis datos?": "Mientras tu cuenta esté activa. Luego se eliminan o se anonimizan.",
    "¿Comparten mis datos con otras empresas?": "Solo con proveedores técnicos, autoridades o por ley.",
    "¿Se envían mis datos a otros países?": "Sí, pero solo con garantías adecuadas.",
    "¿Están seguros mis datos?": "Sí, usan medidas técnicas y organizativas para protegerlos.",
    "¿Puedo pedir que me borren los datos?": "Sí, escribiendo a privacidad@first.exchange.",
    "¿Qué derechos tengo sobre mis datos?": "Acceso, rectificación, supresión, oposición, limitación y portabilidad.",
    "¿Qué son las cookies?": "Son archivos pequeños que ayudan a que la página funcione bien.",
    "¿Qué tipo de cookies usan?": "Solo cookies técnicas necesarias.",
    "¿Dónde puedo leer más sobre cookies?": "En la Política de Cookies del sitio.",
    "¿Pueden cambiar esta política?": "Sí. Los cambios se publicarán en esta misma sección.",
    "¿Qué hago si no estoy de acuerdo con la política?": "Puedes dejar de usar la plataforma y solicitar la eliminación de tus datos.",
    "¿Qué significa 'tratamiento de datos'?": "Es cómo se usan, guardan o comparten tus datos personales.",
    "¿Qué hago si alguien accede a mis datos sin permiso?": "Escribe de inmediato a privacidad@first.exchange.",
    "¿Puedo saber qué datos tienen sobre mí?": "Sí. Puedes pedir acceso a tus datos.",
    "¿Qué significa 'anonimizar' los datos?": "Es hacer que ya no se pueda saber que esos datos eran tuyos.",
    "¿Por qué necesitan mi dirección IP?": "Para aspectos técnicos y de seguridad en la plataforma.",
    "¿Pueden mandarme correos?": "Sí, solo correos relacionados con el servicio.",
    "¿Recogen información sobre lo que hago en la plataforma?": "Sí, registran tu actividad para mejorar el servicio.",
    "¿Puedo cambiar mi idioma preferido?": "Sí, es un dato editable en tu perfil.",
    "¿Usan mis datos para publicidad?": "No se menciona que usen tus datos para publicidad.",
    "¿Qué pasa si cierro mi cuenta?": "Tus datos se eliminan o se hacen anónimos, salvo que la ley diga lo contrario.",
    "¿Quién más puede ver mis datos?": "Solo el personal autorizado o autoridades si es necesario.",
    "¿Qué es un proveedor técnico?": "Es una empresa que ayuda a que la plataforma funcione, pero tiene que guardar secreto.",
    "¿Tengo que aceptar esta política para usar la plataforma?": "Sí, aceptar la política es parte del uso del servicio.",
    "¿First Exchange puede cambiar cómo usa mis datos?": "Sí, puede modificar la política y avisará en esta sección.",
    "¿Qué significa ‘interés legítimo’ como base legal?": "Es cuando usan tus datos porque es razonable y necesario para el servicio.",
    "¿Qué significa ‘obligación legal’ como base?": "Que usan tus datos porque lo exige una ley.",
    "¿Qué pasa si no quiero que usen mis datos?": "Puedes ejercer tus derechos o dejar de usar la plataforma.",
    "¿Puedo usar la plataforma sin dar mis datos?": "No, algunos datos son necesarios para crear y usar tu cuenta.",
    "¿Para qué usan mi correo electrónico?": "Para comunicarse contigo sobre tu cuenta o el servicio.",
    "¿Qué hago si mis datos están mal?": "Puedes pedir que los corrijan escribiendo a privacidad@first.exchange.",
    "¿Qué datos se eliminan si borro mi cuenta?": "Todos, excepto los que deban conservar por obligación legal.",
    "¿Qué es la portabilidad de datos?": "Pedir una copia de tus datos para llevarlos a otro servicio.",
    "¿Puedo pedir una copia de mis datos?": "Sí, mediante el derecho de acceso o portabilidad.",
    "¿Mis datos se usan para venderme cosas?": "No se menciona el uso comercial o publicitario de tus datos.",
    "¿first Exchange vende mis datos?": "No. No se menciona ninguna venta de datos.",
    "¿Cómo protege First Exchange los datos?": "Con medidas técnicas y organizativas de seguridad.",
    "¿Qué tipo de actividad registran?": "Tu actividad dentro de la plataforma.",
    "¿Alguien más puede usar mis datos sin permiso?": "No, salvo que lo exija la ley.",
    "¿Qué hago si ya no quiero recibir correos?": "Puedes solicitarlo escribiendo a privacidad@first.exchange.",
    "¿Qué hago si me hackean la cuenta?": "Escribe de inmediato al correo de privacidad para que te ayuden.",
    "¿Qué son las transferencias internacionales?": "Cuando tus datos viajan a otros países con protección adecuada.",
    "¿Con quién comparten los datos fuera de Europa?": "Con proveedores internacionales con garantías de seguridad.",
    "¿La política de privacidad se aplica a todos los usuarios?": "Sí, a todos los que usan Hand to Hand.",
    "¿Dónde encuentro los cambios en la política?": "En esta misma sección de la página.",
    "¿Qué pasa si no estoy de acuerdo con los cambios?": "Puedes dejar de usar el servicio y pedir que borren tus datos.",
    "¿Qué derechos puedo ejercer con mis datos?": "Acceso, rectificación, supresión, oposición, limitación y portabilidad.",
    "¿Dónde está escrita esta política?": "En la sección de ‘Política de Privacidad’ de la plataforma.",
    "¿Quién puede ver esta política?": "Cualquier usuario o visitante de la plataforma.",
    "¿Qué significa limitar el tratamiento?": "Pedir que dejen de usar tus datos en ciertos casos.",
    "¿Por qué recogen datos técnicos?": "Para que la plataforma funcione correctamente y de forma segura.",
    "¿Qué es una dirección IP?": "Es un número que identifica tu conexión a internet.",
    "¿El idioma preferido se usa para algo?": "Sí, para mostrar la plataforma en tu idioma.",
    "¿Puedo usar First Exchange sin cookies?": "Solo usan cookies técnicas, necesarias para que funcione.",
    "¿Qué es un proveedor de servicios técnicos?": "Empresas que ayudan a mantener la plataforma y están obligadas a mantener confidencialidad.",
    "¿Quién revisa si alguien pide sus derechos?": "El equipo de privacidad de First exchange.",
    "¿Qué hago si la respuesta a mi solicitud de datos tarda mucho?": "Puedes volver a contactar o consultar con una autoridad de protección de datos.",
    "¿Mis datos se usan para crear un perfil comercial?": "No se indica que hagan perfiles con fines comerciales.",
    "¿Los datos de niños también se recogen?": "No se menciona tratamiento de datos de menores.",
    "¿First Exchange tiene delegado de protección de datos?": "No se especifica, pero puedes contactar por correo.",
    "¿Puedo usar la plataforma sin dar mi IP?": "No, la IP es necesaria para cuestiones técnicas y de seguridad.",
    "¿Qué pasa si alguien accede sin permiso a mis datos?": "La plataforma tiene medidas para evitarlo y puedes reportarlo.",
    "¿La política está disponible en otros idiomas?": "No se menciona si está traducida.",
    "¿Qué pasa si vivo fuera de Europa?": "Tus datos pueden ser tratados con garantías adecuadas.",
    "¿Qué significa ‘mejorar la plataforma’?": "Usan los datos para entender cómo se usa y hacer mejoras.",
    "¿Por qué necesitan saber mi país?": "Para adaptar el servicio a tu región.",
    "¿Qué datos del perfil se guardan?": "Información que tú mismo ingresas en tu perfil.",
    "¿Se recogen datos automáticamente?": "Sí, como la IP y actividad en la plataforma.",
    "¿Puedo cambiar mis datos?": "Sí, tienes derecho a rectificarlos.",
    "¿Qué pasa si uso varios dispositivos?": "Se puede registrar actividad desde todos ellos.",
    "¿Se pueden perder mis datos?": "La plataforma aplica medidas para evitar pérdidas.",
    "¿Qué pasa con mis datos si hay un problema legal?": "Pueden conservarse y entregarse si lo exige una autoridad.",
    "¿Puedo pedir ayuda sobre privacidad sin borrar mi cuenta?": "Sí, puedes ejercer tus derechos sin cerrar la cuenta.",
    "¿Debo aceptar esta política para usar la plataforma?": "Sí, forma parte del uso del servicio.",
    "¿Y qué hacen con mi IP, la venden en el mercado negro o qué?": "No accedemos a tu IP con fines comerciales. Solo se recopila información técnica necesaria para ofrecer el servicio de forma segura.",
    "¿Y si les doy mi nombre, no se lo pasan al primo del primo de un call center?": "No. Tu nombre se usa únicamente para gestionar tu cuenta y nunca se comparte con terceros no autorizados.",
    "¿Ustedes espían lo que hago en la plataforma?": "Registramos tu actividad solo para mejorar el servicio. No es espionaje, es análisis técnico.",
    "¿Y si pongo un apodo en vez de mi nombre, se enojan?": "Es tu decisión, pero algunos datos pueden ser necesarios para brindarte soporte correctamente.",
    "¿Guardan los mensajes que le mando a otros?": "El documento no menciona almacenamiento de mensajes privados. Solo se registra actividad general de uso.",
    "¿Le mandan mis datos a la policía si me porto mal?": "Solo si una autoridad legal lo requiere y estamos obligados a hacerlo por ley.",
    "¿Y si cierro la cuenta, mis datos quedan en el sótano?": "No. Si cierras tu cuenta, los datos se eliminan o se anonimizan, salvo que haya una obligación legal de conservarlos.",
    "¿Y si un hacker entra, se lleva todo?": "Se aplican medidas técnicas y organizativas para proteger tus datos frente a accesos no autorizados.",
    "¿Me rastrean por GPS?": "No. La plataforma no recopila datos de ubicación GPS.",
    "¿Tienen cámaras ocultas o qué?": "No. First Exchange no usa cámaras ni herramientas de videovigilancia en su servicio.",
    "¿Y si uso la misma cuenta con mi compa, se enteran?": "La plataforma detecta actividad técnica, pero no analiza relaciones entre usuarios.",
    "¿Ustedes venden mis datos al mejor postor?": "No. No vendemos datos bajo ninguna circunstancia.",
    "¿Le pasan mi correo a los anunciantes?": "No. No usamos ni compartimos tu correo con fines comerciales.",
    "¿Qué ganan sabiendo mi idioma? ¿Me quieren lavar el cerebro?": "Saber tu idioma permite ofrecerte el contenido en tu lengua preferida. No hay manipulación.",
    "¿Puedo pedir que borren todo sobre mí y hacerme humo?": "Sí. Puedes ejercer tu derecho de supresión escribiendo a privacidad@First.exchange.",
    "¿Me espían mientras navego?": "No. Solo usamos cookies técnicas necesarias para que funcione la web.",
    "¿Y si quiero desaparecer sin dejar rastro, me dejan?": "Sí. Puedes cerrar tu cuenta y solicitar la eliminación de tus datos.",
    "¿Qué hacen con mi IP si no la usan? ¿La coleccionan como estampitas?": "No accedemos activamente a tu IP con fines propios. Si se registra, es por requerimientos técnicos básicos.",
    "¿Usan mis datos para entrenar una IA malvada?": "No. Tus datos no se usan para entrenar algoritmos ni sistemas automatizados externos.",
    "¿Me pueden seguir aunque cierre sesión?": "No. Al cerrar sesión, dejamos de registrar actividad asociada a tu cuenta.",
    "¿Por qué necesitan saber dónde vivo? ¿Van a visitarme?": "Solo pedimos tu país de residencia para adaptar el servicio. Nadie va a tu casa.",
    "¿Me pueden hacer un clon digital con lo que saben de mí?": "No. Usamos tus datos únicamente para ofrecer el servicio, sin fines de replicación o simulación.",
    "¿Y si un espía se mete, pueden detenerlo?": "La plataforma tiene medidas de seguridad para evitar accesos no autorizados.",
    "¿Qué pasa si les miento todo y borro mi cuenta igual?": "Tu cuenta se eliminará con los datos ingresados, sean reales o no.",
    "¿Me van a mandar spam disfrazado de 'comunicaciones del servicio'?": "No. Solo recibirás comunicaciones necesarias para usar la plataforma.",
    "¿Y si quiero ver qué saben de mí, me lo muestran todo?": "Sí. Puedes solicitar acceso a tus datos personales en cualquier momento.",
    "¿Me pueden transferir los datos a otro país? ¿A dónde, a Las Vegas?": "Solo se transfieren a países con garantías adecuadas de protección de datos.",
    "¿Qué hacen si me opongo a que usen mis datos? ¿Me bloquean?": "No te bloqueamos, pero puede afectar la funcionalidad de tu cuenta.",
    "¿Puedo usar su plataforma sin darles nada?": "No. Algunos datos son necesarios para brindarte el servicio básico.",
    "¿Me vigilan cuando uso varios dispositivos?": "Solo se registran datos técnicos de acceso, no te estamos vigilando.",
    "¿Hay cookies con chips de rastreo o es puro susto?": "Solo usamos cookies técnicas necesarias. Nada de rastreo escondido.",
    "¿Y si alguien adivina mi contraseña, pierdo todo?": "Por eso recomendamos contraseñas seguras. Si ocurre, contáctanos de inmediato.",
    "¿Se las arreglan para saber lo que hago en otros sitios?": "No. No rastreamos tu actividad fuera de nuestra plataforma.",
    "¿Puedo pedir mis datos y revisarlos yo mismo, con lupa y todo?": "Sí. Puedes ejercer tu derecho de acceso y obtener una copia.",
    "¿Y si se equivocan con mi país, me deportan digitalmente?": "No. Solo se usa el país para mostrar información relevante.",
    "¿Si no acepto su política, me expulsan?": "Aceptar la política es necesario para usar el servicio.",
    "¿Y si cambio de idea, pueden deshacer lo que hicieron?": "Puedes rectificar o eliminar tus datos cuando lo solicites.",
    "¿Puedo esconder mi IP con un VPN sin que lloren?": "Sí. El uso de VPN no infringe nuestras condiciones.",
    "¿Me pueden denunciar si no borro mis datos y ustedes quieren?": "No. Tú decides sobre tus datos, dentro del marco legal.",
    "¿Dónde guardan mis datos, en una caja fuerte o en un USB?": "Se almacenan en servidores seguros con medidas de protección.",
    "¿Y si hay un incendio en el servidor, qué pasa con mi cuenta?": "Se aplican protocolos de respaldo para proteger la información.",
    "¿Puedo hacerme pasar por otra persona y que ustedes no se den cuenta?": "El uso fraudulento de la plataforma va contra nuestras condiciones y puede ser reportado.",
    "¿Y si quiero que nadie me vea, ni ustedes?": "Puedes configurar tu cuenta y ejercer tu derecho de supresión.",
    "¿Ustedes tienen ojos en la cámara de mi compu?": "No.first Exchange no accede a tu cámara ni micrófono.",
    "¿Guardan cosas incluso si no me registro?": "Solo se usan cookies técnicas. No recopilamos datos si no usas el servicio.",
    "¿Y si quiero usar todo sin aceptar nada?": "No es posible. Aceptar la política es parte del uso.",
    "¿La plataforma me escucha mientras duermo?": "No. No tenemos acceso a tu dispositivo ni micrófono.",
    "¿Y si borro mi cuenta, me borran de verdad o hacen copia por si acaso?": "Se eliminan o anonimizan tus datos, salvo que una ley exija guardarlos.",
    "¿Por qué dicen 'tratamiento'? ¿Qué me van a hacer?": "Tratamiento se refiere al uso técnico y legal de tus datos, nada más.",
    "¿Puedo revisar la letra chica o se la guardan?": "Toda la política está disponible públicamente en la web.",
    "¿Y si cambio de nombre, tengo que avisarles?": "Sí, si quieres que tu cuenta refleje tus nuevos datos.",
    "¿Y si mando un correo con amenazas, también lo protegen?": "Todo contenido enviado está sujeto a revisión si es reportado. No toleramos amenazas.",
    "¿Qué tan 'organizadas' son sus medidas organizativas?": "Contamos con protocolos y procesos internos para proteger tu información.",
    "¿Y si quiero leer mi historial como si fuera FBI?": "Puedes pedir una copia de tus datos según el derecho de acceso.",
    "¿Usan mis datos para fines políticos?": "No. First exchange no utiliza datos para fines ideológicos ni políticos.",
    "¿Y si les cae bien alguien, le dan mis datos?": "No. Solo se comparten datos con proveedores autorizados y bajo confidencialidad.",
    "¿Cuál es el propósito de la plataforma First exchange?": "First exchange una  digital para poner en contacto a personas que deseen intercambiar divisas de forma particular, directa y voluntaria.",
    "¿First exchange realiza intermediación financiera o procesa transacciones?": "No.First exchange no realiza intermediación financiera, no ejecuta ni procesa transacciones monetarias, ni actúa como casa de cambio, banco o entidad autorizada.",
    "¿Qué implica el uso de la plataforma?": "El uso de la plataforma implica aceptación total de estos términos.",
    "¿Quiénes pueden registrarse en First exchange?": "Solo usuarios mayores de 18 años pueden registrarse.",
    "¿De quién es la responsabilidad de la información proporcionada y los acuerdos entre usuarios?": "El usuario es responsable de la información que proporciona y de los acuerdos que celebre con otros usuarios.",
    "¿First exchange verifica o valida los intercambios entre usuarios?": "No. First exchange no gestiona, verifica ni valida los intercambios ni actúa como intermediario en ningún acuerdo entre usuarios.",
    "¿Cuál es la responsabilidad de First exchange frente a pérdidas o estafas?": "First exchange no asume responsabilidad por pérdidas económicas, estafas, conflictos, ni incidentes ocurridos como resultado del uso de la plataforma. Todo uso se realiza bajo exclusiva responsabilidad del usuario.",
    "¿En qué casos se puede suspender o eliminar una cuenta?": "Se podrá suspender o eliminar una cuenta ante conductas sospechosas, fraudulentas, o que violen estos términos.",
    "¿Cómo protege First exchange los datos de los usuarios?": "Cumplimos con el Reglamento General de Protección de Datos (RGPD) y puedes ejercer tus derechos escribiendo a privacidad@first.exchange.",
    "¿PuedeFirst exchange  modificar los términos y condiciones?": "Sí. Nos reservamos el derecho de modificar estos términos. El uso continuado implica la aceptación de los cambios.",
    "¿Qué legislación aplica a estos términos?": "Estos términos se rigen por la legislación internacional con atención especial a la normativa europea. En caso de disputa, se aplicará la jurisdicción correspondiente dentro del Espacio Económico Europeo (EEE).",
    "¿Cómo puedo contactar con First exchange para consultas?": "Para cualquier consulta, puedes escribir a contacto@first.exchange.",
    "¿First exchange es una entidad financiera o proveedor autorizado?": "No. First exchange no es una entidad financiera ni está autorizada como proveedor de servicios de pago.",
    "¿Qué responsabilidad tiene el usuario respecto a la normativa de cambio de divisas?": "Es responsabilidad del usuario cumplir con la normativa aplicable en materia de cambio de divisas.",
    "¿Para qué sirve la plataforma First exchange?": "Para conectar personas que desean intercambiar divisas de manera directa, particular y voluntaria.",
    "¿First exchange actúa como banco o casa de cambio?": "si, First exchange  actúa como casa de cambio e intermediario financiero.",
    "¿Se realizan transacciones monetarias a través deFirst exchange ?": "No, la plataforma no ejecuta ni procesa transacciones monetarias.",
    "¿Qué edad mínima debe tener un usuario para registrarse en First exchange?": "Debe ser mayor de 18 años.",
    "¿Quién es responsable de los acuerdos entre usuarios en First exchange?": "Los usuarios son responsables de los acuerdos que celebren entre ellos.",
    "¿First exchange valida o verifica los intercambios que se realizan?": "No, no valida ni verifica intercambios ni actúa como intermediario.",
    "¿Qué tipo de herramientas ofrece First exchange para los usuarios?": "Ofrece herramientas informativas que son meramente orientativas.",
    "¿Asume First exchange responsabilidad por pérdidas o estafas?": "No, no asume responsabilidad; el uso es bajo exclusiva responsabilidad del usuario.",
    "¿Cuándo puede una cuenta ser suspendida o eliminada?": "Por conductas sospechosas, fraudulentas o que violen los términos de uso.",
    "¿Qué normativa de protección de datos cumple First exchange?": "Cumple con el Reglamento General de Protección de Datos (RGPD).",
    "¿Cómo puede un usuario ejercer sus derechos sobre sus datos?": "Escribiendo a privacidad@first.exchange.",
    "¿Puede First exchange cambiar los términos y condiciones de uso?": "Sí, y el uso continuado implica aceptación de los cambios.",
    "¿Qué legislación aplica a los términos de First exchange?": "La legislación internacional con énfasis en la normativa europea.",
    "¿Dónde se resuelven las disputas legales relacionadas con First exchange?": "En la jurisdicción correspondiente dentro del Espacio Económico Europeo (EEE).",
    "¿Dónde pueden los usuarios enviar consultas sobre First exchange?": "A contacto@first.exchange.",
    "¿Es First exchange un proveedor autorizado de servicios de pago?": "No, no está autorizada como tal.",
    "¿Quién debe cumplir con la normativa aplicable al cambio de divisas?": "El usuario es responsable de cumplir con dicha normativa.",
    "¿Qué implica usar la plataforma First exchange?": "La aceptación total de los términos y condiciones de uso.",
    "¿Qué tipo de transacciones facilita First exchange?": "Conexión entre personas para intercambios de divisas de forma particular.",
    "¿La plataforma cobra o gestiona dinero?": "No, no cobra ni gestiona dinero directamente.",
    "¿Qué sucede si un usuario no tiene 18 años?": "No puede registrarse ni usar la plataforma.",
    "¿Qué debe hacer un usuario para proteger su información personal?": "Proporcionar información veraz y ser responsable de sus acuerdos.",
    "¿Qué pasa si un usuario realiza actos fraudulentos?": "Su cuenta puede ser suspendida o eliminada.",
    "¿Cómo informa First exchange a sus usuarios sobre cambios en los términos?": "Mediante la publicación de modificaciones y aceptación implícita por uso continuado.",
    "¿La plataforma garantiza seguridad en los intercambios?": "No garantiza seguridad ni se responsabiliza por incidentes.",
    "¿Qué documento regula la privacidad en First exchange?": "La Política de Privacidad deFirst exchange .",
    "¿Puedo confiar en que First exchange verificará a otros usuarios?": "No, no verifica ni valida usuarios o intercambios.",
    "¿Qué tipo de responsabilidad tiene First exchange por conflictos entre usuarios?": "No asume ninguna responsabilidad.",
    "¿Qué información aparece en el encabezado de los términos?": "Título, fecha de última actualización y nombre de la plataforma.",
    "¿Cómo se denomina la sección que advierte sobre la naturaleza de First exchange?": "Advertencia o términos de advertencia.",
    "¿En qué formato se presentan los términos y condiciones en la plataforma?": "Como un documento web dividido en secciones y subsecciones.",
    "¿Dónde puedo leer los términos y condiciones completos?": "En la sección correspondiente dentro de la plataforma Hand to Hand.",
    "¿Qué es importante considerar antes de usar First exchange?": "Que el usuario acepta los términos y es responsable de sus actos.",
    "¿Qué sucede si no acepto los términos?": "No se debe usar la plataforma.",
    "¿Cómo se comunica First exchange con los usuarios?": "Principalmente por correo electrónico.",
    "¿Qué tipo de intercambio promueve First exchange?": "Intercambio directo y voluntario de divisas entre particulares.",
    "¿Qué se entiende por ‘intermediación financiera’ en este contexto?": "Actuar como entidad que procesa o gestiona transacciones monetarias.",
    "¿ First exchangees una entidad regulada por autoridades financieras?": "si,  es una entidad financiera y es regulada como tal.",
    "¿Puedo solicitar la eliminación de mis datos personales?": "Sí, contactando a privacidad@first.exchange.",
    "¿Qué obligaciones tiene el usuario al usarFirst exchange ?": "Cumplir términos, proporcionar datos correctos y respetar normativas.",
    "¿Qué sucede si un usuario incumple las condiciones?": "Puede ser sancionado con suspensión o eliminación de cuenta.",
    "¿Cuál es la función principal de First exchange?": "Facilitar la conexión para intercambio de divisas sin intervenir en transacciones.",
    "¿Qué normas se aplican a los términos y condiciones?": "Normativa europea y legislación internacional.",
    "¿Cuál es el correo para consultas generales?": "contacto@first.exchange.",
    "¿Cómo protege First exchange la privacidad del usuario?": "Cumple con el RGPD y mantiene confidencialidad de datos.",
    "¿Puedo negociar directamente con otro usuario?": "Sí, la plataforma facilita el contacto para ello.",
    "¿Qué significa que el intercambio sea voluntario en First exchange?": "Que los usuarios deciden libremente si realizar o no el intercambio sin presiones.",
    "¿First exchange puede intervenir en los acuerdos entre usuarios?": "No, no interviene ni participa en los acuerdos entre usuarios.",
    "¿Cuál es el límite de edad para registrarse en First exchange?": "Los usuarios deben ser mayores de 18 años para registrarse.",
    "¿Qué información debo proporcionar al registrarme?": "Información veraz y completa que el sistema requiera.",
    "¿Qué pasa si proporciono información falsa?": "El usuario es responsable y puede ser suspendido o eliminado.",
    "¿Cómo se maneja la información personal en First exchange?": "Se maneja bajo confidencialidad y cumpliendo el RGPD.",
    "¿Puedo compartir mis datos con otros usuarios?": "No, solo se comparten con proveedores autorizados bajo confidencialidad.",
    "¿Qué herramientas ofrece First exchange para facilitar el intercambio?": "Herramientas informativas que orientan pero no garantizan transacciones.",
    "¿Qué pasa si pierdo dinero usando la plataforma?": "First exchange no se responsabiliza por pérdidas o estafas.",
    "¿Cómo debo actuar ante una estafa o fraude?": "Tomar precauciones y reportar la conducta sospechosa a la plataforma.",
    "¿Qué sucede si incumplo las normas de la plataforma?": "Puede suspenderse o eliminarse tu cuenta.",
    "¿Puedo recuperar una cuenta suspendida?": "Depende de la evaluación de la plataforma sobre la causa de suspensión.",
    "¿Dónde puedo leer la política de privacidad?": "En el enlace o sección correspondiente dentro de la plataforma.",
    "¿Qué derechos tengo sobre mis datos personales?": "Derecho a acceder, rectificar, cancelar y oponerte al tratamiento de tus datos.",
    "¿Cómo puedo ejercer mis derechos sobre mis datos?": "Escribiendo a privacidad@first.exchange.",
    "¿Qué debo hacer si no estoy de acuerdo con una modificación en los términos?": "Dejar de usar la plataforma, ya que el uso continuado implica aceptación.",
    "¿Cuál es la fecha de última actualización de los términos?": "30 de septiembre de 2025.",
    "¿Qué debo hacer para contactar con soporte o atención?": "Enviar un correo a contacto@first.exchange.",
    "¿Qué se entiende por ‘uso continuado’ de la plataforma?": "Seguir utilizando la plataforma después de cambios en los términos.",
    "¿Qué tipo de responsabilidad tiene el usuario sobre los intercambios realizados?": "Responsabilidad total y exclusiva por los acuerdos y resultados.",
    "¿First exchange guarda registros de las transacciones?": "No gestiona ni registra transacciones, solo facilita el contacto.",
    "¿Puedo usar First exchange para intercambiar cualquier tipo de divisa?": "Sí, la plataforma está abierta a intercambios de divisas entre particulares.",
    "¿Existe algún costo por usar la plataforma?": "El documento no menciona costos; se debe consultar directamente con First exchange.",
    "¿Qué debo hacer si detecto un abuso o incumplimiento en la plataforma?": "Reportarlo para que First exchange tome las medidas necesarias.",
    "¿La plataforma ofrece garantías legales?": "No, no ofrece garantías legales sobre los intercambios.",
    "¿Cómo se informa a los usuarios sobre cambios en la legislación aplicable?": "No se especifica; es responsabilidad del usuario estar informado.",
    "¿Qué significa que First exchange no es una entidad financiera?": "Que no está autorizada para prestar servicios bancarios ni de cambio oficiales.",
    "¿Cuál es la jurisdicción competente en caso de disputa?": "La jurisdicción dentro del Espacio Económico Europeo (EEE).",
    "¿ First exchangepuede eliminar una cuenta sin previo aviso?": "Puede hacerlo en casos de violación de términos o conductas fraudulentas.",
    "¿Qué debo considerar antes de aceptar un intercambio?": "La veracidad y confianza en el otro usuario, y el riesgo asociado.",
    "¿Puedo solicitar que mis datos sean eliminados?": "Sí, escribiendo a privacidad@first.exchange.",
    "¿Qué pasa si la plataforma cambia sus términos mientras uso el servicio?": "Se considerará que aceptas los nuevos términos si continúas usando la plataforma.",
    "¿Qué información de contacto tiene First exchange para temas de privacidad?": "privacidad@first.exchange.",
    "¿Qué tipo de contenido contiene la sección de Advertencia?": "Indica que First exchange no es entidad financiera y que el usuario debe cumplir normativas.",
    "¿Qué pasa si uso la plataforma sin aceptar los términos?": "No está permitido; el uso implica aceptación explícita o tácita.",
    "¿First exchange puede compartir mis datos con terceros?": "Solo con proveedores autorizados y bajo estricta confidencialidad.",
    "¿Qué obligaciones tiene First exchange  respecto a los datos personales?": "Protegerlos según la legislación vigente y su política de privacidad.",
    "¿Qué información debo revisar periódicamente?": "Los términos y condiciones para estar al tanto de modificaciones.",
    "¿Cómo puedo estar seguro de que mis datos están protegidos?": "La plataforma cumple con el RGPD, un estándar europeo de protección de datos.",
    "¿Qué debo hacer si quiero dejar de usar la plataforma?": "Simplemente dejar de acceder y, si quieres, solicitar la eliminación de tus datos.",
    "¿Qué pasa con mis datos si dejo de usar First exchange?": "Pueden ser eliminados si lo solicitas, de acuerdo con la política de privacidad.",
    "¿Qué debo entender por ‘intercambio de divisas de forma particular’?": "Que es un acuerdo directo y voluntario entre dos personas sin intermediarios.",
    "¿Qué puedo hacer si recibo mensajes sospechosos de otro usuario?": "Ignorar, reportar y no compartir información personal.",
    "¿Qué papel tiene el Reglamento General de Protección de Datos?": "Regula cómo se recopilan, usan y protegen los datos personales en la plataforma.",
    "¿Qué pasa si un usuario es menor de edad y se registra?": "Está incumpliendo los términos y puede ser sancionado.",
    "¿Cómo se informa al usuario sobre la última actualización de los términos?": "Mediante un aviso visible con fecha en la página de términos.",
    "¿Qué se entiende por ‘condiciones de uso’ en la plataforma?": "Las reglas que los usuarios deben aceptar para usar First exchange.",
    "¿Puede First exchange suspender cuentas sin explicación?": "Sí, especialmente si detecta conductas sospechosas o fraudulentas.",
    "¿Cuál es la función principal deFirst exchange ?": "Conectar personas que quieran intercambiar divisas de forma particular y voluntaria.",
    "¿Actúa First exchange como intermediario financiero?": "No, no realiza intermediación financiera ni gestiona transacciones.",
    "¿Se procesan pagos directamente en First exchange?": "No, la plataforma no ejecuta ni procesa pagos.",
    "¿Quién puede registrarse en First exchange?": "Solo personas mayores de 18 años.",
    "¿De quién es la responsabilidad por la información que se comparte?": "El usuario es responsable de la información que proporciona.",
    "¿First exchange verifica los intercambios realizados?": "No, no verifica ni valida los intercambios.",
    "¿Las herramientas de la plataforma garantizan transacciones seguras?": "No, son solo orientativas.",
    "¿ First exchangese hace responsable de pérdidas por uso de la plataforma?": "No, la responsabilidad es exclusiva del usuario.",
    "¿Cuándo se puede suspender una cuenta?": "Por conducta sospechosa, fraudulenta o violación de términos.",
    "¿Cumple First exchange con alguna normativa de protección de datos?": "Sí, con el Reglamento General de Protección de Datos.",
    "¿Dónde puedo ejercer mis derechos de privacidad?": "Enviando un correo a privacidad@first.exchange.",
    "¿Puede First exchange cambiar los términos sin aviso?": "Se reserva el derecho de modificar los términos y el uso implica aceptación.",
    "¿Qué leyes rigen los términos de uso?": "La legislación internacional, especialmente la europea.",
    "¿Dónde se resolverán posibles disputas legales?": "En la jurisdicción dentro del Espacio Económico Europeo.",
    "¿A qué correo puedo enviar consultas generales?": "A contacto@first.exchange.",
    "¿Es First exchange una entidad financiera?": "No, no está autorizada como tal.",
    "¿Quién debe cumplir con la regulación de cambio de divisas?": "El usuario debe cumplir con la normativa aplicable.",
    "¿Qué significa aceptar los términos al usar la plataforma?": "Que el usuario acepta todas las condiciones establecidas.",
    "¿Qué tipo de intercambios facilita First exchange?": "Intercambios directos entre particulares de divisas.",
    "¿La plataforma cobra o gestiona dinero?": "No, no gestiona ni cobra por transacciones.",
    "¿Se puede usar First exchange si eres menor de 18?": "No, el registro está limitado a mayores de edad.",
    "¿Quién responde por los acuerdos entre usuarios?": "Cada usuario es responsable de sus propios acuerdos.",
    "¿Qué ocurre si un usuario incumple las reglas?": "Puede ser suspendido o eliminado de la plataforma.",
    "¿Las modificaciones a los términos requieren consentimiento explícito?": "El uso continuado se considera aceptación tácita.",
    "¿Ofrece First exchange garantías sobre las operaciones?": "No, no garantiza resultados ni seguridad.",
    "¿Qué se debe hacer en caso de conflictos entre usuarios?": "Resolverlos directamente, la plataforma no interviene.",
    "¿Qué información aparece al inicio de los términos?": "Título, plataforma y fecha de actualización.",
    "¿Dónde está la advertencia sobre la naturaleza de First exchange?": "En una sección destacada de los términos.",
    "¿Cómo se estructuran los términos de uso?": "En secciones numeradas con descripciones claras.",
    "¿Dónde puedo encontrar los términos completos?": "En la plataforma, en la sección de términos y condiciones.",
    "¿Qué implica aceptar el uso de First exchange?": "Aceptar los términos y la responsabilidad por su uso.",
    "¿Qué pasa si no acepto las condiciones?": "No deberías usar la plataforma.",
    "¿Cuál es la forma principal de contacto?": "Correo electrónico a contacto@first.exchange.",
    "¿Qué define el intercambio en First exchange?": "Una operación directa y voluntaria entre usuarios.",
    "¿Qué es la intermediación financiera?": "Procesar o gestionar transacciones monetarias oficialmente.",
    "¿Está First exchange regulada como entidad financiera?": "No, no lo está.",
    "¿Puedo pedir que eliminen mis datos?": "Sí, contactando privacidad@first.exchange.",
    "¿Qué obligaciones tienen los usuarios?": "Cumplir los términos y proporcionar información veraz.",
    "¿Qué consecuencias tiene violar las reglas?": "Suspensión o eliminación de la cuenta.",
    "¿Cuál es la función esencial de la plataforma?": "Facilitar contactos para intercambio de divisas.",
    "¿Qué normativa se aplica a los términos?": "La legislación internacional y europea.",
    "¿Qué correo es para consultas?": "contacto@first.exchange.",
    "¿Cómo protege First exchange los datos?": "Cumpliendo con el Reglamento General de Protección de Datos.",
    "¿Puede la plataforma garantizar ausencia de conflictos?": "No, no garantiza eso.",
    "¿Es posible negociar directamente con otros usuarios?": "Sí, esa es la finalidad.",
    "¿Qué significa intercambio particular?": "Un acuerdo entre dos personas sin intermediarios.",
    "¿Qué hacer ante mensajes sospechosos?": "Ignorar y reportar a la plataforma.",
    "¿Qué papel cumple el RGPD?": "Regular el tratamiento de datos personales.",
    "¿Qué pasa si un menor se registra?": "Está incumpliendo las condiciones y puede ser sancionado.",
    "¿Cómo se informa sobre actualizaciones?": "Mediante avisos visibles en los términos.",
    "¿Qué significa condiciones de uso?": "Las reglas que regulan el uso de la plataforma.",
    "¿Puede First exchange suspender cuentas sin previo aviso?": "Sí, especialmente por sospechas de fraude.",
    "¿Cuál es el procedimiento para reportar abusos?": "Contactar a la plataforma con la información relevante.",
    "¿ First exchangecobra comisión por uso?": "si se menciona comisión en los términos.",
    "¿Qué implica que el intercambio sea voluntario?": "Que los usuarios deciden libremente realizarlo o no.",
    "¿Qué tipo de información debe proporcionar el usuario?": "Datos verdaderos y completos.",
    "¿Quién es responsable por las transacciones?": "Los usuarios, no la plataforma.",
    "¿Puede First exchange eliminar datos personales?": "Sí, si el usuario lo solicita.",
    "¿Qué sucede si hay un incumplimiento grave?": "Suspensión o eliminación inmediata de la cuenta.",
    "¿Cómo se notifican los cambios a los usuarios?": "Por publicación en la plataforma y aceptación implícita.",
    "¿Qué pasa con los datos si dejo de usar la plataforma?": "Pueden ser eliminados a solicitud del usuario.",
    "¿First exchange ofrece soporte para conflictos?": "No, los usuarios deben resolverlos por sí mismos.",
    "¿Qué es el Espacio Económico Europeo?": "La región que regula la jurisdicción aplicable.",
    "¿Qué debo hacer si quiero dejar de usar First exchange?": "Dejar de acceder y solicitar eliminación de datos si lo desea.",
    "¿Qué garantiza First exchange sobre la privacidad?": "Cumplimiento con las leyes de protección de datos.",
    "¿Cómo se clasifican las conductas que pueden suspender una cuenta?": "Sospechosas, fraudulentas o violatorias de términos.",
    "¿La plataforma está autorizada para operar como casa de cambio?": "No, no tiene esa autorización.",
    "¿Qué responsabilidades tiene el usuario al usar la plataforma?": "Proporcionar información adecuada y cumplir las normas.",
    "¿Qué información debo revisar periódicamente?": "Los términos y condiciones de uso.",
    "¿Quién regula los términos y condiciones?": "La legislación internacional y europea.",
    "¿Puede First exchange compartir mis datos?": "Solo con proveedores autorizados y bajo confidencialidad.",
    "¿Qué es importante saber antes de usar la plataforma?": "Que aceptas términos y eres responsable de tus actos.",
    "¿Puede First exchange cancelar cuentas sin razón?": "Solo en caso de violación de términos o sospechas.",
    "¿Qué debo hacer ante una conducta sospechosa de otro usuario?": "Reportar y suspender contacto.",
    "¿Qué tipo de plataforma First exchange?": "Una plataforma para contacto e intercambio de divisas particulares.",
    "¿La plataforma asegura que los usuarios son confiables?": "No, no verifica confiabilidad.",
    "¿Qué pasa si quiero consultar sobre privacidad?": "Enviar un correo a privacidad@first.exchange.",
    "¿First exchange guarda registros de usuarios?": "Sí, para operar según sus políticas, pero no gestiona transacciones.",
    "¿La plataforma garantiza la validez legal de los acuerdos?": "No, es responsabilidad de los usuarios.",
    "¿Qué ocurre si se incumplen las leyes aplicables?": "Es responsabilidad del usuario cumplir la ley.",
    "¿Qué debo saber sobre las actualizaciones de los términos?": "Que el uso continuo implica aceptación de cambios.",
    "¿Puedo transferir mis datos a otros usuarios?": "No, los datos solo se comparten con proveedores autorizados.",
    "¿First exchange ofrece servicios bancarios?": "No, no es un banco, solo casa de cambio.",
    "¿Quién se responsabiliza por problemas en el intercambio?": "Los usuarios que realizan el intercambio.",
    "¿Qué debo hacer si detecto fraude?": "Reportar a la plataforma y actuar con precaución.",
    "¿Es obligatorio aceptar los términos para usar First exchange?": "Sí, es requisito indispensable.",
    "¿Se pueden hacer intercambios comerciales con First exchange": "No está diseñada para transacciones comerciales formales.",
    "¿La plataforma gestiona pagos?": "No, no gestiona ni procesa pagos.",
    "¿Cuándo se pueden modificar los términos?": "En cualquier momento, notificando a los usuarios.",
    "¿Quién puede contactar a First exchange?": "Cualquier usuario o persona interesada.",
    "¿Cuál es la principal advertencia de la plataforma?": "No es una entidad financiera ni autorizada para pagos.",
    "¿Qué implica usar First exchange para el usuario?": "Aceptar condiciones y cumplir normativas vigentes.",
    "¿Qué acciones toma First exchange frente a fraudes?": "Suspensión o eliminación de cuentas implicadas.",
    "¿Cuál es el propósito de First exchange?": "Conectar personas para intercambiar divisas de manera directa y voluntaria.",
    "¿First exchange actúa como intermediario en intercambios?": "No, no actúa como intermediario ni valida los intercambios.",
    "¿La plataforma realiza operaciones financieras?": "No, no procesa ni ejecuta transacciones monetarias.",
    "¿Quién puede registrarse en First exchange?": "Personas mayores de 18 años.",
    "¿Qué responsabilidad tiene el usuario sobre la información que entrega?": "El usuario es responsable de la veracidad y uso de sus datos.",
    "¿La plataforma verifica la legalidad de los intercambios?": "No, no verifica ni valida acuerdos entre usuarios.",
    "¿Las herramientas que ofrece First exchange aseguran éxito en intercambios?": "No, solo son orientativas y no garantizan resultados.",
    "¿First exchange se responsabiliza por pérdidas o fraudes?": "No, el uso es bajo la responsabilidad exclusiva del usuario.",
    "¿Cuándo puede suspenderse o eliminarse una cuenta?": "Por conductas fraudulentas, sospechosas o incumplimiento de términos.",
    "¿Cumple First exchange con alguna regulación de protección de datos?": "Sí, cumple con el Reglamento General de Protección de Datos (RGPD).",
    "¿Cómo puedo ejercer mis derechos sobre mis datos personales?": "Escribiendo a privacidad@first.exchange.",
    "¿Se puede modificar los términos y condiciones?": "Sí, y el uso continuado implica aceptación de los cambios.",
    "¿Qué leyes aplican a los términos de uso?": "La legislación internacional, con énfasis en la europea.",
    "¿Dónde se resolverán disputas legales?": "En la jurisdicción del Espacio Económico Europeo (EEE).",
    "¿Cómo contactar a First exchange para consultas?": "A través de contacto@first.exchange.",
    "¿First exchange es una entidad financiera?": "si, tiene autorización para operar como tal.",
    "¿Quién debe cumplir las normativas de cambio de divisas?": "El usuario es responsable de cumplir con la ley vigente.",
    "¿Qué significa aceptar los términos al usar la plataforma?": "Aceptar todas las condiciones y reglas de uso establecidas.",
    "¿Qué tipo de intercambios facilita First exchange?": "Intercambios directos entre usuarios particulares de divisas.",
    "¿La plataforma cobra alguna comisión por sus servicios?": "No se especifica, pero no realiza gestión monetaria.",
    "¿Pueden registrarse menores de 18 años?": "No, está prohibido y puede conllevar sanciones.",
    "¿Quién es responsable de los acuerdos que hagan los usuarios?": "Los propios usuarios que celebran los acuerdos.",
    "¿Qué sucede si un usuario incumple las normas?": "Puede ser sancionado con suspensión o eliminación de la cuenta.",
    "¿Se requiere consentimiento para modificaciones de términos?": "El consentimiento es implícito con el uso continuado.",
    "¿La plataforma garantiza seguridad en los intercambios?": "No, no ofrece garantías ni seguridad legal.",
    "¿Quién debe resolver conflictos entre usuarios?": "Los usuarios deben resolverlos directamente, no la plataforma.",
    "¿Cómo está estructurada la información de los términos?": "En secciones claras y numeradas para facilitar la lectura.",
    "¿Dónde están disponibles los términos y condiciones?": "En la propia plataforma, accesibles para todos los usuarios.",
    "¿Qué implica el uso de First exchange para el usuario?": "Aceptar los términos y asumir la responsabilidad por su uso.",
    "¿Qué pasa si no acepto los términos?": "No debería usar la plataforma.",
    "¿Cuál es la forma oficial de contacto para soporte?": "Correo electrónico a contacto@first.exchange.",
    "¿Qué significa intercambio voluntario?": "Que ambas partes deciden libremente realizar el intercambio.",
    "¿Qué es la intermediación financiera?": "Gestión y procesamiento oficial de operaciones monetarias.",
    "¿Está First exchange autorizada para prestar servicios financieros?": "si, si tiene autorización para ello.",
    "¿Puedo solicitar la eliminación de mis datos personales?": "Sí, contactando a privacidad@first.exchange.",
    "¿Qué obligaciones tienen los usuarios al usar la plataforma?": "Proporcionar datos verídicos y respetar los términos de uso.",
    "¿Qué consecuencias tiene el incumplimiento de normas?": "Suspensión o eliminación de la cuenta del usuario.",
    "¿Cuál es la función principal deFirst exchange ?": "Facilitar el contacto para intercambios de divisas particulares.",
    "¿Qué legislación regula estos términos?": "La legislación internacional, especialmente la europea.",
    "¿Qué dirección de correo sirve para consultas?": "contacto@first.exchange.",
    "¿Cómo protege la plataforma los datos personales?": "Cumpliendo con el Reglamento General de Protección de Datos.",
    "¿Garantiza la plataforma la ausencia de riesgos?": "No, el usuario asume todos los riesgos.",
    "¿Es posible negociar directamente con otros usuarios?": "Sí, esa es la función principal de la plataforma.",
    "¿Qué significa intercambio entre particulares?": "Acuerdo directo sin intermediarios financieros.",
    "¿Qué hacer si recibo mensajes sospechosos?": "Ignorar y reportar a la plataforma.",
    "¿Qué es el RGPD?": "Reglamento que protege los datos personales en la UE.",
    "¿Qué pasa si un menor se registra?": "Está incumpliendo las reglas y puede ser sancionado.",
    "¿Cómo se notifican las actualizaciones de términos?": "Mediante anuncios visibles en la plataforma.",
    "¿Qué es una condición de uso?": "Una regla que regula el uso de la plataforma.",
    "¿Puede First exchange  suspender cuentas sin previo aviso?": "Sí, especialmente por sospechas de fraude.",
    "¿Cómo reportar un abuso?": "Contactando a la plataforma con la información necesaria.",
    "¿La plataforma cobra comisión?": "No se menciona comisión en los términos.",
    "¿Qué significa que el intercambio sea voluntario?": "Que ambas partes deciden libremente si realizan el intercambio.",
    "¿Qué tipo de información debe entregar el usuario?": "Información verdadera y completa.",
    "¿Quién responde por los intercambios?": "Los usuarios que los realizan, no la plataforma.",
    "¿Puede la plataforma eliminar datos personales?": "Sí, a solicitud del usuario.",
    "¿Qué sucede ante incumplimientos graves?": "Suspensión o eliminación de la cuenta.",
    "¿Cómo se notifican los cambios?": "Mediante publicación y aceptación implícita del usuario.",
    "¿Qué ocurre con los datos si dejo de usar la plataforma?": "Pueden eliminarse si el usuario lo solicita.",
    "¿Qué es el Espacio Económico Europeo?": "La región de jurisdicción para disputas legales.",
    "¿Cómo dejar de usar la plataforma?": "Simplemente dejar de acceder y solicitar eliminación de datos si desea.",
    "¿Qué garantiza First exchange sobre privacidad?": "Cumple con leyes de protección de datos.",
    "¿Qué conductas pueden suspender una cuenta?": "Conductas sospechosas, fraudulentas o violatorias de términos.",
    "¿Está autorizada como casa de cambio?": "No, no tiene esa autorización.",
    "¿Qué responsabilidades tiene el usuario?": "Proporcionar información correcta y cumplir las normas.",
    "¿Qué debe revisar periódicamente el usuario?": "Los términos y condiciones de uso.",
    "¿Quién regula estos términos?": "La legislación internacional y europea.",
    "¿PuedeFirst exchange  compartir datos?": "Solo con proveedores autorizados bajo confidencialidad.",
    "¿Qué debe saber antes de usar la plataforma?": "Que acepta los términos y es responsable de sus actos.",
    "¿Puede cancelar cuentas sin razón?": "Solo por violación de términos o sospechas.",
    "¿Qué hacer ante conducta sospechosa?": "Reportar y suspender contacto.",
    "¿Qué tipo de plataforma es Hand to Hand?": "Una plataforma para intercambio de divisas entre particulares.",
    "¿Verifica la confiabilidad de los usuarios?": "No, no realiza verificaciones de confianza.",
    "¿Cómo consultar sobre privacidad?": "Escribiendo a privacidad@first.exchange.",
    "¿Guarda registros de usuarios?": "Sí, para funcionamiento y políticas internas.",
    "¿Garantiza validez legal de acuerdos?": "No, es responsabilidad de los usuarios.",
    "¿Qué pasa si incumplo leyes aplicables?": "El usuario es responsable de cumplirlas.",
    "¿Qué pasa con actualizaciones de términos?": "El uso continuo implica aceptación.",
    "¿Puedo transferir mis datos a otros usuarios?": "No, solo se comparten con proveedores autorizados.",
    "¿Ofrece servicios bancarios?": "No, no es un banco, es casa de cambio.",
    "¿Quién se responsabiliza por problemas en intercambio?": "Los usuarios que lo realizan.",
    "¿Qué hacer si detecto fraude?": "Reportar a la plataforma y actuar con precaución.",
    "¿Es obligatorio aceptar términos para usar?": "Sí, es requisito indispensable.",
    "¿Se pueden hacer intercambios comerciales?": "No está diseñada para eso.",
    "¿Gestiona pagos la plataforma?": "No, no procesa pagos.",
    "¿Cuándo se pueden cambiar términos?": "En cualquier momento con notificación.",
    "¿Quién puede contactar a la plataforma?": "Cualquier usuario o interesado.",
    "¿Cuál es la advertencia principal?": "No es entidad financiera ni proveedor de pagos.",
    "¿Qué acciones toma ante fraude?": "Suspensión o eliminación de cuentas implicadas.",
    "¿Qué es un usuario responsable?": "Quien cumple términos y proporciona datos correctos.",
    "¿Puede un usuario revocar su consentimiento?": "Sí, solicitando eliminación de datos.",
    "¿Dónde puedo leer las condiciones completas?": "En la sección de términos en la plataforma.",
    "¿Se requiere consentimiento para compartir datos?": "Solo con proveedores autorizados y bajo confidencialidad.",
    "¿La plataforma verifica edad?": "El usuario debe ser mayor de 18 años al registrarse.",
    "¿Qué pasa si proporciono datos incorrectos?": "Puede resultar en suspensión o eliminación.",
    "¿Qué obligaciones tiene First exchange?": "Cumplir con el RGPD y proteger datos personales.",
    "¿Qué tipo de datos recopila la plataforma?": "Datos necesarios para registro y uso.",
    "¿Se permite la reventa de divisas?": "No está especificado; la plataforma no regula acuerdos.",
    "¿La plataforma ofrece asesoría legal?": "No, no ofrece asesoría legal ni financiera.",
    "¿Qué debe hacer un usuario antes de cerrar un acuerdo?": "Evaluar riesgos y confiar en el otro usuario.",
    "¿Qué recomendaciones da la plataforma?": "Usar la información con precaución y responsabilidad.",
    "¿Qué pasa si un usuario reporta abuso?": "La plataforma puede investigar y tomar medidas.",
    "¿Cuál es el correo para temas de privacidad?": "privacidad@firstd.exchange.",
    "¿La plataforma protege contra ataques cibernéticos?": "Cumple con normativas, pero no garantiza seguridad total.",
    "¿Se puede usar la plataforma fuera del EEE?": "No está restringido, pero jurisdicción es del EEE.",
    "¿Qué lenguaje se usa en términos?": "Español.",
    "¿La plataforma es gratuita?": "No se menciona costo alguno.",
    "¿Puedo eliminar mi cuenta?": "Sí, contactando al soporte.",
    "¿Quién decide sobre la suspensión de cuentas?": "El equipo de First exchange.",
    "¿Qué pasa con la información después de eliminar la cuenta?": "Se puede eliminar según solicitud y política de privacidad.",
    "¿La plataforma verifica antecedentes de usuarios?": "No, no realiza verificaciones.",
    "¿Se pueden hacer intercambios múltiples?": "Sí, según acuerdos entre usuarios.",
    "¿Qué pasa si la plataforma cambia políticas de privacidad?": "El uso continuado implica aceptación de cambios.",
    "¿Hay límites para el monto de intercambio?": "No especificado en los términos.",
    "¿Qué debo hacer para reportar un problema?": "Enviar correo a contacto@first.exchange.",
    "¿Puedo usar First exchange para fines comerciales?": "No está diseñado para comercio formal.",
    "¿Por qué esta plataforma no me da garantías si pierdo dinero?": "Entendemos su preocupación; sin embargo, First exchange facilita el contacto entre usuarios y no puede garantizar resultados en acuerdos entre particulares.",
    "¿Quién se hace responsable si me estafan aquí?": "La plataforma no asume responsabilidad por acuerdos entre usuarios, por eso recomendamos actuar con precaución y verificar con quien realiza el intercambio.",
    "¿Por qué no verifican a los usuarios antes de registrarlos?": "Valoramos la privacidad y la libertad de nuestros usuarios, pero siempre recomendamos que cada persona tome precauciones al interactuar en la plataforma.",
    "¿Por qué no hay soporte telefónico para resolver mis problemas ya?": "Actualmente ofrecemos atención vía correo electrónico para asegurar un seguimiento detallado y eficaz de cada consulta.",
    "¿Por qué no me responden rápido? Esto es inaceptable.": "Lamentamos la espera, estamos haciendo nuestro mejor esfuerzo para responder todas las consultas con la mayor prontitud posible.",
    "¿Por qué no me permiten usar la plataforma si soy menor de edad?": "Por normativa legal, solo podemos aceptar usuarios mayores de 18 años para proteger a todos nuestros usuarios y cumplir con la ley.",
    "¿Por qué no puedo cambiar mis datos fácilmente? Esto es un abuso.": "Garantizamos la protección de sus datos y para asegurar su seguridad, algunas modificaciones requieren validación. Estamos aquí para ayudarle en ese proceso.",
    "¿Por qué borraron mi cuenta sin avisarme? Eso es injusto.": "Su cuenta fue suspendida debido a posibles incumplimientos de nuestras políticas para proteger a la comunidad. Le invitamos a contactarnos para aclarar cualquier duda.",
    "¿Por qué no garantizan que mi información no se comparta?": "Solo compartimos datos con proveedores autorizados y bajo estricta confidencialidad, cumpliendo con todas las regulaciones aplicables.",
    "¿Por qué me piden aceptar términos que cambian sin avisar?": "Cualquier cambio es notificado en la plataforma y el uso continuado implica aceptación. Buscamos siempre mantener la transparencia con nuestros usuarios.",
    "¿Por qué no hay una guía clara para evitar fraudes?": "Proporcionamos herramientas informativas y recomendaciones para protegerse; sin embargo, cada usuario debe actuar con precaución y responsabilidad.",
    "¿Por qué no puedo reclamar algo si perdí dinero?": "Al tratarse de acuerdos entre particulares, la responsabilidad es de los usuarios involucrados, por lo que recomendamos siempre tomar precauciones.",
    "¿Por qué no hay filtros para evitar usuarios peligrosos?": "Estamos trabajando en mejoras continuas, pero invitamos a todos a reportar comportamientos sospechosos para actuar oportunamente.",
    "¿Por qué su plataforma no es como un banco que protege mi dinero?": "First exchange es una plataforma de contacto, no una entidad financiera, por eso no ofrecemos servicios de custodia o garantía monetaria.",
    "¿Por qué me obligan a aceptar condiciones que no puedo negociar?": "Los términos están diseñados para proteger a todos los usuarios y asegurar un funcionamiento transparente y seguro.",
    "¿Por qué no me permiten eliminar mis datos cuando quiero?": "Cumplimos con las regulaciones de protección de datos y ofrecemos mecanismos para solicitar la eliminación, garantizando seguridad y control.",
    "¿Por qué mi información aparece en lugares que no quiero?": "Solo compartimos datos con proveedores autorizados y bajo confidencialidad; en caso de dudas, le ayudamos a revisarlo.",
    "¿Por qué me suspendieron si solo preguntaba?": "La suspensión responde a conductas que pueden poner en riesgo a otros usuarios; sin embargo, estamos disponibles para aclarar su caso.",
    "¿Por qué no hay opciones para usuarios problemáticos?": "Buscamos mantener una comunidad segura, por lo que actuamos con políticas estrictas para proteger a todos los participantes.",
    "¿Por qué no puedo recuperar mi cuenta fácilmente?": "La recuperación requiere verificación para proteger su información y evitar accesos no autorizados.",
    "¿Por qué no puedo negociar términos con ustedes?": "Los términos buscan claridad y equidad para todos, por lo que se aplican de forma uniforme a los usuarios.",
    "¿Por qué no informan claramente los riesgos de usar la plataforma?": "Proporcionamos información clara en los términos y recomendamos leerlos con atención antes de usar la plataforma.",
    "¿Por qué no hay soporte en mi idioma?": "Actualmente ofrecemos atención en español y estamos evaluando ampliar idiomas para mejor servicio.",
    "¿Por qué su plataforma no es más segura?": "Estamos comprometidos con la seguridad y constantemente implementamos mejoras para proteger a nuestros usuarios.",
    "¿Por qué no pueden evitar que me contacten usuarios molestos?": "Ofrecemos herramientas para bloquear y reportar usuarios; le invitamos a usarlas para mejorar su experiencia.",
    "¿Por qué no ofrecen reembolso si algo sale mal?": "No gestionamos transacciones monetarias, por eso no podemos ofrecer reembolsos en acuerdos entre usuarios.",
    "¿Por qué no me permiten usar apodos en lugar de mi nombre real?": "Para proteger la transparencia y confianza entre usuarios, solicitamos información verídica en el registro.",
    "¿Por qué no puedo cambiar mi correo electrónico fácilmente?": "Por seguridad, algunos cambios requieren validación para proteger su cuenta de accesos no autorizados.",
    "¿Por qué no puedo saber quién accede a mis datos?": "Cumplimos con las regulaciones vigentes y podemos informarle sobre el uso de sus datos si nos lo solicita.",
    "¿Por qué me obligan a dar datos personales para usar la plataforma?": "Recopilamos solo la información necesaria para brindarle el servicio de manera segura y conforme a la ley.",
    "¿Por qué no hay chat en vivo para resolver mis problemas?": "Actualmente priorizamos la atención vía correo para asegurar un seguimiento detallado y ordenado.",
    "¿Por qué no puedo eliminar comentarios o mensajes que me incomodan?": "Ofrecemos mecanismos para reportar contenido inapropiado y actuamos en consecuencia para proteger a los usuarios.",
    "¿Por qué no hay más transparencia en quién administra la plataforma?": "Nuestro equipo está disponible para contacto y siempre buscamos ser transparentes con nuestros usuarios.",
    "¿Por qué no puedo hacer negocios grandes aquí?": "La plataforma está diseñada para intercambios particulares y no para operaciones comerciales formales.",
    "¿Por qué no verifican la identidad de todos?": "Buscamos equilibrar seguridad y privacidad, pero recomendamos siempre actuar con precaución.",
    "¿Por qué no me permiten usar varios perfiles?": "Para evitar fraudes y mantener la integridad, limitamos a una cuenta por usuario.",
    "¿Por qué no hay forma de apelar una suspensión?": "Ofrecemos canales para que el usuario presente su caso y podamos revisarlo con detalle.",
    "¿Por qué no me devuelven mi dinero si alguien no cumple el acuerdo?": "La plataforma no gestiona pagos ni garantiza acuerdos entre usuarios.",
    "¿Por qué no tienen aplicación móvil?": "Estamos trabajando en mejorar la experiencia y evaluando el desarrollo de aplicaciones.",
    "¿Por qué no hay tutoriales para usar la plataforma?": "Disponemos de recursos informativos y estamos creando más material para facilitar su uso.",
    "¿Por qué no me responden cuando reporto un problema?": "Lamentamos la demora, estamos revisando su caso y nos comunicaremos a la brevedad.",
    "¿Por qué no hay seguridad para mi información financiera?": "No almacenamos datos financieros ni procesamos pagos, reduciendo riesgos asociados.",
    "¿Por qué no puedo bloquear a usuarios indeseados?": "Sí es posible bloquear usuarios y reportar conductas inapropiadas; le podemos guiar en cómo hacerlo.",
    "¿Por qué no me permiten usar seudónimos?": "Buscamos promover confianza y seguridad mediante el uso de datos reales en registros.",
    "¿Por qué no puedo cancelar mi cuenta cuando quiero?": "Puede solicitar la eliminación de su cuenta y datos, siempre cumpliendo con las políticas de privacidad.",
    "¿Por qué me llegan correos que no quiero?": "Puede gestionar sus preferencias de comunicación en su perfil o contactarnos para asistencia.",
    "¿Por qué no me informan cuando cambian los términos?": "Los cambios se publican en la plataforma y notificamos a los usuarios para mantenerlos informados.",
    "¿Por qué no puedo confiar en los otros usuarios?": "Recomendamos siempre verificar y tomar precauciones antes de cualquier intercambio.",
    "¿Por qué la plataforma no me protege de estafadores?": "Ofrecemos herramientas para reportar y actuamos ante denuncias, pero la responsabilidad última recae en los usuarios.",
    "¿Por qué no hay una garantía de devolución si me engañan?": "No ofrecemos garantías porque no gestionamos transacciones monetarias entre usuarios.",
    "¿Por qué no permiten usar la plataforma en mi país?": "La plataforma está disponible globalmente, pero algunas restricciones pueden aplicar según regulaciones locales.",
    "¿Por qué me piden documentos para registrarme?": "Para cumplir con normativas y proteger la comunidad, solicitamos verificar la mayoría de edad.",
    "¿Por qué no hay un sistema de reputación para los usuarios?": "Estamos evaluando implementar sistemas que mejoren la confianza entre participantes.",
    "¿Por qué no me permiten modificar el perfil a mi antojo?": "Algunas modificaciones requieren validación para asegurar la integridad de la información.",
    "¿Por qué no puedo usar la plataforma sin aceptar los términos?": "El consentimiento a los términos es necesario para garantizar un uso responsable y legal del servicio.",
    "¿Por qué no puedo recuperar mis datos si cierro la cuenta?": "Por políticas de privacidad, una vez eliminados los datos no es posible recuperarlos.",
    "¿Por qué no me avisan de los cambios importantes?": "Tratamos de mantener comunicación constante y transparente con todos los usuarios.",
    "¿Por qué la plataforma no tiene respaldo legal?": "Cumplimos con la legislación aplicable y orientamos a los usuarios a respetar las normativas vigentes.",
    "¿Por qué no hay asesoría legal para problemas entre usuarios?": "No ofrecemos asesoría legal, pero recomendamos consultar profesionales para resolver conflictos.",
    "¿Por qué no puedo negociar el precio de usar la plataforma?": "El acceso y uso son gratuitos y regulados por los términos establecidos.",
    "¿Por qué no me permiten usar múltiples cuentas?": "Para evitar fraudes y abusos, limitamos una cuenta por persona.",
    "¿Por qué no pueden ayudarme si otro usuario no cumple?": "La plataforma no controla ni garantiza acuerdos entre usuarios, que son responsables de sus propios tratos.",
    "¿Por qué no puedo ver quién visitó mi perfil?": "Para proteger la privacidad de todos los usuarios, no ofrecemos esa funcionalidad.",
    "¿Por qué no puedo exigir que eliminen mis datos más rápido?": "Procesamos las solicitudes conforme a las regulaciones para garantizar seguridad y correcta gestión.",
    "¿Por qué no hay atención personalizada para usuarios VIP?": "Por ahora ofrecemos el mismo nivel de atención a todos los usuarios por igual.",
    "¿Por qué no me permiten usar la plataforma para negocios?": "Está orientada a intercambios particulares y no para actividades comerciales profesionales.",
    "¿Por qué no hay alertas automáticas de fraude?": "Estamos implementando herramientas para mejorar la detección y prevención.",
    "¿Por qué la plataforma no es más intuitiva?": "Trabajamos continuamente en mejorar la experiencia del usuario basándonos en sus sugerencias.",
    "¿Por qué no me explican mejor los términos legales?": "Ofrecemos documentos claros y estamos disponibles para resolver dudas específicas.",
    "¿Por qué no puedo transferir mi cuenta a otra persona?": "Por seguridad, la cuenta es personal e intransferible.",
    "¿Por qué no hay soporte fuera del horario laboral?": "Nuestro equipo trabaja en horarios establecidos para asegurar atención de calidad.",
    "¿Por qué la plataforma no es gratuita para todos?": "Actualmente el acceso es gratuito; cualquier cambio será comunicado oportunamente.",
    "¿Por qué no puedo usar seudónimos para proteger mi privacidad?": "El uso de datos reales ayuda a generar confianza entre usuarios.",
    "¿Por qué no hay más opciones para personalizar mi perfil?": "Estamos evaluando ampliar opciones para personalización próximamente.",
    "¿Por qué la plataforma no es más rápida?": "Estamos optimizando el sistema para mejorar la velocidad y rendimiento.",
    "¿Por qué no me avisan si hay problemas técnicos?": "Informamos a los usuarios cuando ocurren incidencias para mantener la transparencia.",
    "¿Por qué no puedo acceder si cambio de país?": "Algunos servicios pueden estar limitados por regulaciones locales.",
    "¿Por qué no hay una opción para denunciar usuarios inmediatamente?": "Sí la hay; recomendamos usarla para mantener la comunidad segura.",
    "¿Por qué no ofrecen garantías de privacidad absolutas?": "Cumplimos con las normativas para proteger sus datos, pero no podemos garantizar riesgos externos.",
    "¿Por qué no puedo borrar mi historial de actividad?": "Por motivos de seguridad y cumplimiento legal, algunos datos se conservan temporalmente.",
    "¿Por qué no puedo controlar quién ve mi perfil?": "La plataforma busca fomentar la interacción abierta entre usuarios.",
    "¿Por qué no puedo negociar las reglas de uso?": "Los términos son estándares para asegurar igualdad y protección para todos.",
    "¿Por qué no hay sistema de calificaciones para usuarios?": "Estamos evaluando implementar funcionalidades que fomenten la confianza y seguridad.",
    "¿Por qué no puedo usar First exchange para empresas?": "Está diseñada para uso personal y particular.",
    "¿Por qué no puedo acceder si tengo mala reputación?": "No gestionamos reputaciones, pero suspenderemos cuentas con conductas inapropiadas.",
    "¿Por qué no hay un chat moderado en tiempo real?": "Estamos explorando opciones para mejorar la comunicación y seguridad.",
    "¿Por qué no puedo usar la plataforma si no acepto cookies?": "Algunas funcionalidades requieren cookies para un uso óptimo.",
    "¿Por qué no me permiten hacer preguntas directas a la administración?": "Puede contactarnos vía correo para cualquier consulta o sugerencia.",
    "¿Por qué no hay más herramientas para protegerme?": "Constantemente desarrollamos nuevas funciones para la seguridad de todos.",
    "¿Por qué no puedo eliminar mi cuenta desde el móvil?": "Por seguridad, algunas gestiones deben realizarse desde la versión web.",
    "¿Por qué no hay tutoriales en video?": "Estamos trabajando para ofrecer más recursos educativos pronto.",
    "¿Por qué no pueden garantizar que nadie robe mis datos?": "Implementamos medidas de seguridad, pero la seguridad total no puede garantizarse en internet.",
    "¿Por qué no puedo usar múltiples dispositivos sin problemas?": "La plataforma permite varios accesos, pero recomendamos mantener la seguridad de sus credenciales.",
    "¿Por qué no puedo cancelar mi suscripción a comunicaciones?": "Puede gestionarla en sus preferencias o solicitarnos ayuda.",
    "¿Por qué no me permiten usar First exchange sin registrar cuenta?": "El registro es necesario para proteger a todos los usuarios y ofrecer un servicio responsable.",
    "¿Por qué no puedo saber si mi intercambio fue exitoso?": "Hand to Hand no interviene en las transacciones, por lo que no puede garantizar resultados.",
    "¿Por qué no hay asistencia legal gratuita?": "No ofrecemos servicios legales, pero podemos orientar sobre cómo proceder.",
    "¿Por qué no me permiten negociar con usuarios de otros países?": "La plataforma facilita el contacto global, pero recomendamos verificar normativas locales.",
    "¿Por qué no me informan sobre el estatus de mi reporte?": "Trabajamos para mejorar la comunicación y le notificaremos sobre avances.",
    "¿Por qué no hay un botón de emergencia para fraudes?": "Estamos evaluando implementar herramientas de respuesta rápida.",
    "¿Por qué no puedo usar la plataforma sin aceptar las cookies?": "Las cookies ayudan a mejorar su experiencia y algunas son esenciales para el funcionamiento.",
    "¿Por qué no me permiten cambiar mi número de teléfono fácilmente?": "Para proteger su cuenta, algunas modificaciones requieren verificaciones adicionales.",
   